[project]
name = "langchain-course"
version = "0.1.0"
description = ""
authors = [
    {name = "davidvijay",email = "davidvijay273@gmail.com"}
]
requires-python = ">=3.13,<4.0"
dependencies = [
    "langchain (>=1.4.1,<2.0.0)",
    "langchain-openai (>=1.6.2,<2.0.0)",
    "langchain-tavily (>=0.2.18,<0.3.0)",
    "langgraph (>=1.2.11,<2.0.0)",
    "python-dotenv (>=1.2.3,<2.0.0)",
    "black (>=26.5.1,<27.0.0)",
    "isort (>=9.0.1,<10.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
